[package]
name = "uapi"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
core = { path = "core", package = "uapi-core" }
salloc = { path = "salloc", package = "uapi-salloc", optional = true }
transport = { path = "transport", package = "uapi-transport", optional = true }

[features]
salloc = ["dep:salloc"]
transport = ["dep:transport"]
mrpc = ["core/mrpc"]

# [lib]
# crate-type = ["dylib"]
