addon_engine = "BreakWaterEngine"
tx_channels_replacements = [
    ["MrpcEngine", "BreakWaterEngine", 0, 0],
    ["BreakWaterEngine", "TcpRpcAdapterEngine", 0, 0],
]
rx_channels_replacements = [
    ["TcpRpcAdapterEngine", "BreakWaterEngine", 0, 0],
    ["BreakWaterEngine", "MrpcEngine", 0, 0],
]
group = ["MrpcEngine", "TcpRpcAdapterEngine"]
op = "attach"
config_string = '''
requests_per_sec = 1000
bucket_size = 1000
request_credits = 100
request_timestamp = 10
'''