[package]
name = "uapi-salloc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
uapi = { path = "../core", package = "uapi-core" }

serde = { workspace = true, features = ["derive"] }
static_assertions.workspace = true
