name = "benchmark/parameter_server/inception_v3"
description = "Run rpc_bench_plus benchmark"
group = "parameter_server"
timeout = 15

[[worker]]
host = "danyang-06"
bin = "rpc_bench_plus_server"
args = ""

[[worker]]
host = "danyang-05"
bin = "rpc_bench_plus_client"
args = "-c rdma0.danyang-06 --overwrite InceptionV3"
