name = "rpc_echo"
description = "Run rpc_echo"
group = "rpc_echo"
timeout_secs = 60000
start_delay = 5

[[worker]]
host = "root@rpc-echo-server.c.app-defined-networks.internal"
port = 2345
bin = "rpc_echo_server"
args = ""
term = 2

[[worker]]
host = "root@rpc-echo-frontend.c.app-defined-networks.internal"
port = 2346
bin = "rpc_echo_frontend"
args = ""
term = 2
dependencies = [0]