name = "rpc_echo"
description = "Run rpc_echo"
group = "rpc_echo"
timeout_secs = 60000
start_delay = 5

[[worker]]
host = "root@h3"
port = 2345
bin = "rpc_echo_server"
args = ""
term = 9

[[worker]]
host = "root@h2"
port = 2346
bin = "rpc_echo_frontend"
args = ""
term = 9
dependencies = [0]