name = "launch_phoenix"
description = "Launch phoenix daemon"
group = "launch_phoenix"
timeout_secs = 60000

[[worker]]
host = "root@rpc-echo-server.c.app-defined-networks.internalroot@rpc-echo"
port = 2345
bin = "phoenixos"
args = "-c eval/echo-bench/phoenix.toml"

[[worker]]
host = "root@rpc-echo-frontend.c.app-defined-networks.internal"
port = 2346
bin = "phoenixos"
args = "-c eval/echo-bench/phoenix.toml"