version: "3"
services:
  hotel_frontend:
    image: kristoffstarling/hotel_service:multi
    container_name: 'hotel_frontend'
    hostname: host_frontend
    ports:
    - '2345:22'
    - '5000:5000'
    command: '/usr/sbin/sshd -D'