[package]
name = "mrpc-derive"
version = "0.1.0"
edition = "2021"


[lib]
proc_macro = true

[dependencies]
anyhow.workspace = true
itertools.workspace = true
proc-macro2.workspace = true
quote.workspace = true
syn = { workspace = true, features = [ "extra-traits" ] }
thiserror.workspace = true
