[alias]
# command aliases
rr = "run --release"
build-plan = "build --build-plan -Z unstable-options"

[env]
RUST_BACKTRACE = "1"

[build]
rustflags = [
  # link libphoenix and all engine plugins as dynamic library
  # "-C", "prefer-dynamic", "-C", "rpath",

  # "-C", "codegen-units=1",

  # link all symbols in dependent crates even if they are not actually used (moved to phoenix/build.rs)
  "-C", "link-dead-code",

  # -Zbinary-dep-depinfo allows us to track dependencies of each rlib
  # "-Zunstable-options", "-Zbinary-dep-depinfo",
]
# this is to make sure cargo prints inforamtion about every crates
# incremental = false

[unstable]
# mtime-on-use = true
binary-dep-depinfo = true
