name = "policy/ratelimit/rpc_bench_tput_32b"
description = "Run rpc_bench benchmark"
group = "ratelimit"
timeout_secs = 80

[[worker]]
host = "danyang-03"
bin = "rpc_bench_server"
args = "--port 5002 -l info"

[[worker]]
host = "danyang-02"
bin = "rpc_bench_client"
args = "-c rdma0.danyang-03 --concurrency 32 --req-size 32 --duration 60 -i 0.1 --port 5002 -l info"
dependencies = [0]
