name = "launch_koala"
description = "Launch koala daemon"
group = "launch_koala"
timeout_secs = 600

[[worker]]
host = "danyang-05"
bin = "koala"
args = "--no-ansi"

[[worker]]
host = "danyang-06"
bin = "koala"
args = "--no-ansi"

[[worker]]
host = "danyang-04"
bin = "koala"
args = "--no-ansi"