name = "upgrade_server"
description = "Upgrade server RpcAdapter"
group = "upgrade_server"
timeout_secs = 600

[[worker]]
host = "danyang-06"
bin = "upgrade"
args = "--config eval/liveupgrade/rpc_adapter.toml"