name = "launch_phoenix"
description = "Launch phoenix daemon"
group = "launch_phoenix"
timeout_secs = 6000

[[worker]]
host = "root@localhost"
port = 2345
bin = "phoenixos"
args = "-c eval/hotel-services/phoenix.toml"

[[worker]]
host = "root@localhost"
port = 2346
bin = "phoenixos"
args = "-c eval/hotel-services/phoenix.toml"

[[worker]]
host = "root@localhost"
port = 2347
bin = "phoenixos"
args = "-c eval/hotel-services/phoenix.toml"

[[worker]]
host = "root@localhost"
port = 2348
bin = "phoenixos"
args = "-c eval/hotel-services/phoenix.toml"

[[worker]]
host = "root@localhost"
port = 2349
bin = "phoenixos"
args = "-c eval/hotel-services/phoenix.toml"

